-- Nuevos productos para SayerVision

INSERT INTO public.products (name, serie, category, description, features, applicable_surfaces, environmental_conditions, precautions, requires_primer)
VALUES
  -- Categoría: MURO
  ('Vinil Acrílica Premium Sayer', '100', 'línea arquitectónica', 'Pintura vinil acrílica de excelente poder cubriente y durabilidad para interiores y exteriores.', ARRAY['Lavable', 'Alto rendimiento', 'Secado rápido'], ARRAY['muro-interior', 'muro-exterior', 'concreto', 'block', 'tablaroca', 'yeso'], ARRAY['Seco', 'Templado'], ARRAY['No aplicar con lluvia inminente', 'No ingerir'], false),
  ('Pintura Económica Pro-Muro', 'Eco-50', 'línea arquitectónica', 'Pintura de calidad estándar ideal para proyectos de alto volumen y presupuestos ajustados.', ARRAY['Económica', 'Fácil aplicación'], ARRAY['muro-interior', 'concreto', 'yeso', 'aplanado'], ARRAY['Seco', 'Interior'], ARRAY['Evitar exposición directa a la lluvia antes de secar'], false),
  ('Esmalte Base Agua Sayer', 'EBA-200', 'línea arquitectónica', 'Esmalte ecológico sin olor, ideal para interiores, hospitales y cuartos de niños.', ARRAY['Bajo olor', 'No tóxico', 'Base agua'], ARRAY['muro-interior', 'tablaroca', 'yeso'], ARRAY['Interior', 'Ventilado'], ARRAY['Mantener fuera del alcance de los niños'], false),

  -- Categoría: MADERA
  ('Barniz Tinte Polyform', 'BT-500', 'línea para madera', 'Barniz base solvente que entinta y protege la madera en un solo paso, realzando la veta.', ARRAY['Tinta y barniz', 'Uso interior', 'Brillante'], ARRAY['madera-interior', 'muebles-madera', 'puertas-madera'], ARRAY['Seco', 'Interior'], ARRAY['Aplicar en áreas bien ventiladas', 'Producto inflamable'], true),
  ('Laca Industrial Nitrocelulosa', 'LN-300', 'línea para madera', 'Laca de secado rápido ideal para la industria mueblera. Acabado terso y profesional.', ARRAY['Secado rápido', 'Acabado terso'], ARRAY['muebles-madera', 'madera-interior'], ARRAY['Taller', 'Interior'], ARRAY['Uso exclusivo profesional', 'Altamente inflamable'], true),
  ('Barniz Marino Sayer', 'BM-100', 'línea para madera', 'Barniz de alta resistencia a la humedad y rayos UV, especial para exteriores y climas costeros.', ARRAY['Protección UV', 'Alta resistencia al agua'], ARRAY['madera-exterior', 'puertas-madera'], ARRAY['Exterior', 'Húmedo', 'Soleado'], ARRAY['Aplicar mínimo 3 manos en exterior'], false),

  -- Categoría: METAL
  ('Esmalte Alquidálico Brillante', 'EA-1000', 'línea para metales', 'Esmalte anticorrosivo de alto brillo para proteger y decorar estructuras de metal.', ARRAY['Anticorrosivo', 'Alto brillo', 'Larga duración'], ARRAY['metal-ferroso', 'herreria', 'puertas-metal', 'estructuras-metalicas'], ARRAY['Exterior', 'Interior'], ARRAY['Evitar contacto con la piel', 'Usar solvente para limpieza'], true),
  ('Pintura Epóxica Altos Sólidos', 'EP-500', 'línea para metales', 'Recubrimiento epóxico de dos componentes para tanques, tuberías y ambientes industriales severos.', ARRAY['Resistencia química', 'Dos componentes', 'Uso rudo'], ARRAY['tanques-tuberias', 'estructuras-metalicas'], ARRAY['Industrial', 'Severo'], ARRAY['Requiere catalizador', 'Aplicar con equipo de seguridad'], true),
  ('Primario Anticorrosivo Gris', 'PA-200', 'línea para metales', 'Fondo anticorrosivo de excelente adherencia para preparar superficies metálicas antes del acabado final.', ARRAY['Previene el óxido', 'Excelente anclaje'], ARRAY['metal-ferroso', 'herreria', 'galvanizado'], ARRAY['Exterior', 'Interior'], ARRAY['Tóxico si se ingiere'], false),

  -- Categoría: PISO
  ('Pintura para Tráfico Base Solvente', 'PT-100', 'especialidades y tráfico', 'Pintura de secado rápido para demarcación de calles, estacionamientos y guarniciones.', ARRAY['Secado ultra rápido', 'Alta visibilidad', 'Resistente a la abrasión'], ARRAY['estacionamiento', 'señalizacion', 'piso-exterior'], ARRAY['Exterior', 'Pavimento seco'], ARRAY['Contiene solventes', 'Uso vial'], false),
  ('Epóxico Autonivelante para Pisos', 'EA-800', 'especialidades y tráfico', 'Recubrimiento autonivelante de grado sanitario, ideal para hospitales, laboratorios y bodegas.', ARRAY['Grado sanitario', 'Sin juntas', 'Alta resistencia mecánica'], ARRAY['piso-interior', 'concreto'], ARRAY['Interior', 'Industrial'], ARRAY['Aplicación especializada', 'Proteger de la humedad durante el secado'], true),
  ('Sellador de Poliuretano Transparente', 'PU-300', 'especialidades y tráfico', 'Acabado de poliuretano que sella y protege pisos de concreto estampado o decorativo.', ARRAY['Resistente al tráfico', 'Transparente', 'No se amarillenta'], ARRAY['piso-exterior', 'concreto', 'estacionamiento'], ARRAY['Exterior', 'Soleado'], ARRAY['Evitar aplicación bajo lluvia'], false),

  -- Categoría: ESPECIAL
  ('Impermeabilizante Acrílico 5 Años', 'IMP-5', 'impermeabilizantes', 'Impermeabilizante elastomérico con fibras, alta reflectancia térmica y fácil aplicación.', ARRAY['Fibratado', 'Aislante térmico', 'No requiere tela'], ARRAY['azotea', 'losa', 'impermeabilizacion'], ARRAY['Exterior', 'Soleado'], ARRAY['No aplicar si amenaza lluvia', 'Lavar superficie antes'], false),
  ('Pintura para Albercas Base Caucho', 'AL-100', 'especialidades', 'Pintura especial de caucho clorado, resistente al agua estancada y químicos de piscina.', ARRAY['Resistente al cloro', 'Impermeable', 'Acabado terso'], ARRAY['alberca', 'piscina', 'tanques de agua'], ARRAY['Exterior', 'Inmersión constante'], ARRAY['Dejar secar 7 días antes de llenar la alberca'], false),
  ('Sellador Acrílico 5x1', 'SA-50', 'línea arquitectónica', 'Sellador concentrado para muros, rinde hasta 5 partes de agua por 1 de sellador, tapa el poro del muro.', ARRAY['Alto rendimiento', 'Mejora la adherencia del acabado'], ARRAY['muro-interior', 'muro-exterior', 'concreto', 'block'], ARRAY['Seco', 'Interior o Exterior'], ARRAY['No usar como pintura final'], false);
